### ISSUE TITLE
Unresolved reference: FirebaseApp

### ISSUE THREAD

**Issue by ncjin** [husaynhakeem/android-face-detector#10]
I have download google-service.json. but I have a problem to run it. I google it, and not find a proper solution to solve it

```
C:\Users\XXXX\StudioProjects\android-face-detector\app\src\main\java\husaynhakeem\io\facedetectorapp\MainActivity.kt: (19, 9): Unresolved reference: FirebaseApp
```

**Comment by husaynhakeem** [comment]
The library's been updated to the latest version of MLKit, which doesn't rely on Firebase anymore.
