### ISSUE TITLE
Incompatible with firebase-ml-vision 18.0.1

### ISSUE THREAD

**Issue by edwinckc** [husaynhakeem/android-face-detector#2]
Just leaving a note in case it helps others out.

The dependencies for this project are:
```
    // ML Kit
    implementation 'com.google.firebase:firebase-core:16.0.0'
    implementation 'com.google.firebase:firebase-ml-vision:16.0.0'
```

I tried with 18.0.01 instead of 16.0.0, which resulted in an error about a method not existing.
For `FirebaseVisionFaceDetectorOptions.Builder`,
`setTypeMode(int performanceMode)` was renamed to `setPerformanceMode(int performanceMode)`

Going back to 16.0.0 worked fine.

Thanks Husayn for the library and blog post! Cheers.

**Comment by husaynhakeem** [comment]
Hi @edwinckc. Thanks for pointing that out, a new release (`v1.2`) was just made with the updated dependencies.
